#!/usr/bin/env python3
"""
KiCad Schematic Generator for STM32F103C8 Fan Control System
Based on the working firmware in main_simple.c

This script generates a complete KiCad 7.x schematic file showing:
- STM32F103C8T6 microcontroller
- LM35 temperature sensor (simulated in software)
- 2N2222 transistor motor driver
- DC cooling fan motor
- Protection diode
- Power supply connections
- All labeled pins (PA0-ADC, PA6-PWM, PA9/PA10-UART)
"""

import os
import uuid
from datetime import datetime

def generate_uuid():
    """Generate a KiCad-compatible UUID"""
    return str(uuid.uuid4())

def create_kicad_schematic():
    """Generate the complete KiCad schematic file"""
    
    schematic_content = f'''(kicad_sch (version 20230121) (generator eeschema)

  (uuid {generate_uuid()})

  (paper "A4")

  (title_block
    (title "STM32F103C8 Fan Control System")
    (date "{datetime.now().strftime('%Y-%m-%d')}")
    (rev "1.0")
    (company "Real-Time Systems Project")
    (comment 1 "Temperature-controlled DC fan using PWM")
    (comment 2 "LM35 sensor simulation in software")
    (comment 3 "UART debug output on PA9/PA10")
  )

  (lib_symbols
    (symbol "MCU_ST_STM32F1:STM32F103C8Tx" (in_bom yes) (on_board yes)
      (property "Reference" "U1" (at 0 2.54 0)
        (effects (font (size 1.27 1.27)))
      )
      (property "Value" "STM32F103C8T6" (at 0 0 0)
        (effects (font (size 1.27 1.27)))
      )
      (property "Footprint" "Package_QFP:LQFP-48_7x7mm_P0.5mm" (at 0 -2.54 0)
        (effects (font (size 1.27 1.27)) hide)
      )
      (property "Datasheet" "~" (at 0 -5.08 0)
        (effects (font (size 1.27 1.27)) hide)
      )
      (symbol "STM32F103C8Tx_0_1"
        (rectangle (start -15.24 40.64) (end 15.24 -40.64)
          (stroke (width 0.254) (type default))
          (fill (type background))
        )
      )
      (symbol "STM32F103C8Tx_1_1"
        (pin power_in line (at -2.54 43.18 270) (length 2.54)
          (name "VDD" (effects (font (size 1.27 1.27))))
          (number "1" (effects (font (size 1.27 1.27))))
        )
        (pin power_in line (at -2.54 -43.18 90) (length 2.54)
          (name "VSS" (effects (font (size 1.27 1.27))))
          (number "2" (effects (font (size 1.27 1.27))))
        )
        (pin bidirectional line (at -17.78 10.16 0) (length 2.54)
          (name "PA0-ADC" (effects (font (size 1.27 1.27))))
          (number "10" (effects (font (size 1.27 1.27))))
        )
        (pin bidirectional line (at -17.78 2.54 0) (length 2.54)
          (name "PA6-PWM" (effects (font (size 1.27 1.27))))
          (number "16" (effects (font (size 1.27 1.27))))
        )
        (pin bidirectional line (at -17.78 -2.54 0) (length 2.54)
          (name "PA9-TX" (effects (font (size 1.27 1.27))))
          (number "30" (effects (font (size 1.27 1.27))))
        )
        (pin bidirectional line (at -17.78 -5.08 0) (length 2.54)
          (name "PA10-RX" (effects (font (size 1.27 1.27))))
          (number "31" (effects (font (size 1.27 1.27))))
        )
      )
    )
    
    (symbol "Sensor_Temperature:LM35" (in_bom yes) (on_board yes)
      (property "Reference" "U2" (at 0 5.08 0)
        (effects (font (size 1.27 1.27)))
      )
      (property "Value" "LM35" (at 0 2.54 0)
        (effects (font (size 1.27 1.27)))
      )
      (property "Footprint" "Package_TO_SOT_THT:TO-92_Inline" (at 0 -2.54 0)
        (effects (font (size 1.27 1.27)) hide)
      )
      (symbol "LM35_0_1"
        (rectangle (start -5.08 1.27) (end 5.08 -7.62)
          (stroke (width 0.254) (type default))
          (fill (type background))
        )
      )
      (symbol "LM35_1_1"
        (pin power_in line (at 0 3.81 270) (length 2.54)
          (name "VCC" (effects (font (size 1.27 1.27))))
          (number "1" (effects (font (size 1.27 1.27))))
        )
        (pin output line (at 7.62 -2.54 180) (length 2.54)
          (name "OUT" (effects (font (size 1.27 1.27))))
          (number "2" (effects (font (size 1.27 1.27))))
        )
        (pin power_in line (at 0 -10.16 90) (length 2.54)
          (name "GND" (effects (font (size 1.27 1.27))))
          (number "3" (effects (font (size 1.27 1.27))))
        )
      )
    )
    
    (symbol "Transistor_BJT:2N2222" (pin_names (offset 0) hide) (in_bom yes) (on_board yes)
      (property "Reference" "Q1" (at 5.08 1.905 0)
        (effects (font (size 1.27 1.27)) (justify left))
      )
      (property "Value" "2N2222" (at 5.08 0 0)
        (effects (font (size 1.27 1.27)) (justify left))
      )
      (property "Footprint" "Package_TO_SOT_THT:TO-92_Inline" (at 5.08 -1.905 0)
        (effects (font (size 1.27 1.27) italic) (justify left) hide)
      )
      (symbol "2N2222_0_1"
        (polyline
          (pts
            (xy 0.635 0.635)
            (xy 2.54 2.54)
          )
          (stroke (width 0) (type default))
          (fill (type none))
        )
        (polyline
          (pts
            (xy 0.635 -0.635)
            (xy 2.54 -2.54)
            (xy 2.54 -2.54)
          )
          (stroke (width 0) (type default))
          (fill (type none))
        )
        (polyline
          (pts
            (xy 0.635 1.905)
            (xy 0.635 -1.905)
            (xy 0.635 -1.905)
          )
          (stroke (width 0.508) (type default))
          (fill (type none))
        )
        (circle (center 1.27 0) (radius 2.8194)
          (stroke (width 0.254) (type default))
          (fill (type none))
        )
      )
      (symbol "2N2222_1_1"
        (pin input line (at -5.08 0 0) (length 5.715)
          (name "B" (effects (font (size 1.27 1.27))))
          (number "1" (effects (font (size 1.27 1.27))))
        )
        (pin passive line (at 2.54 -5.08 90) (length 2.54)
          (name "E" (effects (font (size 1.27 1.27))))
          (number "2" (effects (font (size 1.27 1.27))))
        )
        (pin passive line (at 2.54 5.08 270) (length 2.54)
          (name "C" (effects (font (size 1.27 1.27))))
          (number "3" (effects (font (size 1.27 1.27))))
        )
      )
    )
    
    (symbol "Device:R" (pin_numbers hide) (pin_names (offset 0)) (in_bom yes) (on_board yes)
      (property "Reference" "R1" (at 2.032 0 90)
        (effects (font (size 1.27 1.27)))
      )
      (property "Value" "1k" (at 0 0 90)
        (effects (font (size 1.27 1.27)))
      )
      (property "Footprint" "" (at -1.778 0 90)
        (effects (font (size 1.27 1.27)) hide)
      )
      (symbol "R_0_1"
        (rectangle (start -1.016 -2.54) (end 1.016 2.54)
          (stroke (width 0.254) (type default))
          (fill (type none))
        )
      )
      (symbol "R_1_1"
        (pin passive line (at 0 3.81 270) (length 1.27)
          (name "~" (effects (font (size 1.27 1.27))))
          (number "1" (effects (font (size 1.27 1.27))))
        )
        (pin passive line (at 0 -3.81 90) (length 1.27)
          (name "~" (effects (font (size 1.27 1.27))))
          (number "2" (effects (font (size 1.27 1.27))))
        )
      )
    )
    
    (symbol "Diode:1N4007" (pin_numbers hide) (pin_names hide) (in_bom yes) (on_board yes)
      (property "Reference" "D1" (at 0 2.54 0)
        (effects (font (size 1.27 1.27)))
      )
      (property "Value" "1N4007" (at 0 -2.54 0)
        (effects (font (size 1.27 1.27)))
      )
      (property "Footprint" "Diode_THT:D_DO-41_SOD81_P10.16mm_Horizontal" (at 0 -4.445 0)
        (effects (font (size 1.27 1.27)) hide)
      )
      (symbol "1N4007_0_1"
        (polyline
          (pts
            (xy -1.27 1.27)
            (xy -1.27 -1.27)
          )
          (stroke (width 0.254) (type default))
          (fill (type none))
        )
        (polyline
          (pts
            (xy 1.27 0)
            (xy -1.27 0)
          )
          (stroke (width 0) (type default))
          (fill (type none))
        )
        (polyline
          (pts
            (xy 1.27 1.27)
            (xy 1.27 -1.27)
            (xy -1.27 0)
            (xy 1.27 1.27)
          )
          (stroke (width 0.254) (type default))
          (fill (type none))
        )
      )
      (symbol "1N4007_1_1"
        (pin passive line (at -3.81 0 0) (length 2.54)
          (name "K" (effects (font (size 1.27 1.27))))
          (number "1" (effects (font (size 1.27 1.27))))
        )
        (pin passive line (at 3.81 0 180) (length 2.54)
          (name "A" (effects (font (size 1.27 1.27))))
          (number "2" (effects (font (size 1.27 1.27))))
        )
      )
    )
    
    (symbol "Motor:Motor_DC" (pin_names (offset 0)) (in_bom yes) (on_board yes)
      (property "Reference" "M1" (at 2.54 3.81 0)
        (effects (font (size 1.27 1.27)) (justify left))
      )
      (property "Value" "DC_Fan" (at 2.54 1.905 0)
        (effects (font (size 1.27 1.27)) (justify left))
      )
      (property "Footprint" "" (at 0 -2.286 0)
        (effects (font (size 1.27 1.27)) hide)
      )
      (symbol "Motor_DC_0_0"
        (polyline
          (pts
            (xy -1.27 -3.175)
            (xy -2.54 -3.175)
          )
          (stroke (width 0) (type default))
          (fill (type none))
        )
        (polyline
          (pts
            (xy -1.27 3.175)
            (xy -2.54 3.175)
          )
          (stroke (width 0) (type default))
          (fill (type none))
        )
      )
      (symbol "Motor_DC_0_1"
        (circle (center 0 0) (radius 3.2512)
          (stroke (width 0.254) (type default))
          (fill (type none))
        )
        (polyline
          (pts
            (xy -1.27 -1.778)
            (xy 1.27 -1.778)
          )
          (stroke (width 0) (type default))
          (fill (type none))
        )
        (polyline
          (pts
            (xy -1.27 1.905)
            (xy 1.27 1.905)
          )
          (stroke (width 0) (type default))
          (fill (type none))
        )
        (polyline
          (pts
            (xy 0 -5.08)
            (xy 0 -3.8354)
          )
          (stroke (width 0) (type default))
          (fill (type none))
        )
        (polyline
          (pts
            (xy 0 -1.7272)
            (xy 0 -1.651)
          )
          (stroke (width 0) (type default))
          (fill (type none))
        )
        (polyline
          (pts
            (xy 0 1.7272)
            (xy 0 1.905)
          )
          (stroke (width 0) (type default))
          (fill (type none))
        )
        (polyline
          (pts
            (xy 0 5.08)
            (xy 0 3.8354)
          )
          (stroke (width 0) (type default))
          (fill (type none))
        )
      )
      (symbol "Motor_DC_1_1"
        (pin passive line (at 0 7.62 270) (length 2.54)
          (name "+" (effects (font (size 1.27 1.27))))
          (number "1" (effects (font (size 1.27 1.27))))
        )
        (pin passive line (at 0 -7.62 90) (length 2.54)
          (name "-" (effects (font (size 1.27 1.27))))
          (number "2" (effects (font (size 1.27 1.27))))
        )
      )
    )
    
    (symbol "power:+5V" (power) (pin_names (offset 0)) (in_bom yes) (on_board yes)
      (property "Reference" "#PWR" (at 0 -3.81 0)
        (effects (font (size 1.27 1.27)) hide)
      )
      (property "Value" "+5V" (at 0 3.556 0)
        (effects (font (size 1.27 1.27)))
      )
      (symbol "+5V_0_1"
        (polyline
          (pts
            (xy -0.762 1.27)
            (xy 0 2.54)
          )
          (stroke (width 0) (type default))
          (fill (type none))
        )
        (polyline
          (pts
            (xy 0 0)
            (xy 0 2.54)
          )
          (stroke (width 0) (type default))
          (fill (type none))
        )
        (polyline
          (pts
            (xy 0 2.54)
            (xy 0.762 1.27)
          )
          (stroke (width 0) (type default))
          (fill (type none))
        )
      )
      (symbol "+5V_1_1"
        (pin power_in line (at 0 0 90) (length 0) hide
          (name "+5V" (effects (font (size 1.27 1.27))))
          (number "1" (effects (font (size 1.27 1.27))))
        )
      )
    )
    
    (symbol "power:GND" (power) (pin_names (offset 0)) (in_bom yes) (on_board yes)
      (property "Reference" "#PWR" (at 0 -6.35 0)
        (effects (font (size 1.27 1.27)) hide)
      )
      (property "Value" "GND" (at 0 -3.81 0)
        (effects (font (size 1.27 1.27)))
      )
      (symbol "GND_0_1"
        (polyline
          (pts
            (xy 0 0)
            (xy 0 -1.27)
            (xy 1.27 -1.27)
            (xy 0 -2.54)
            (xy -1.27 -1.27)
            (xy 0 -1.27)
          )
          (stroke (width 0) (type default))
          (fill (type none))
        )
      )
      (symbol "GND_1_1"
        (pin power_in line (at 0 0 270) (length 0) hide
          (name "GND" (effects (font (size 1.27 1.27))))
          (number "1" (effects (font (size 1.27 1.27))))
        )
      )
    )
  )

  (junction (at 127 76.2) (diameter 0) (color 0 0 0 0)
    (uuid {generate_uuid()})
  )
  (junction (at 165.1 63.5) (diameter 0) (color 0 0 0 0)
    (uuid {generate_uuid()})
  )

  (wire (pts (xy 50.8 76.2) (xy 62.23 76.2))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 62.23 86.36) (xy 50.8 86.36))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 104.14 66.04) (xy 111.76 66.04))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 111.76 66.04) (xy 111.76 76.2))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 111.76 76.2) (xy 119.38 76.2))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 127 76.2) (xy 134.62 76.2))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 134.62 76.2) (xy 134.62 83.82))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 139.7 83.82) (xy 139.7 63.5))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 139.7 63.5) (xy 165.1 63.5))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 165.1 63.5) (xy 165.1 68.58))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 165.1 76.2) (xy 165.1 81.28))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 165.1 88.9) (xy 165.1 91.44))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 139.7 91.44) (xy 165.1 91.44))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 142.24 91.44) (xy 142.24 93.98))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 127 76.2) (xy 127 93.98))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 88.9 86.36) (xy 88.9 93.98))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 50.8 93.98) (xy 88.9 93.98))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 88.9 93.98) (xy 127 93.98))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 127 93.98) (xy 142.24 93.98))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 165.1 63.5) (xy 165.1 55.88))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 88.9 58.42) (xy 88.9 55.88))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 50.8 68.58) (xy 50.8 55.88))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 50.8 55.88) (xy 88.9 55.88))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )
  (wire (pts (xy 88.9 55.88) (xy 165.1 55.88))
    (stroke (width 0) (type default))
    (uuid {generate_uuid()})
  )

  (text "Temperature Sensor\\n(Software Simulated)" (at 35.56 58.42 0)
    (effects (font (size 1.27 1.27)) (justify left bottom))
    (uuid {generate_uuid()})
  )
  (text "STM32 Controller\\n72MHz ARM Cortex-M3" (at 71.12 45.72 0)
    (effects (font (size 1.27 1.27)) (justify left bottom))
    (uuid {generate_uuid()})
  )
  (text "Fan Driver Circuit\\nPWM @ 8kHz" (at 142.24 45.72 0)
    (effects (font (size 1.27 1.27)) (justify left bottom))
    (uuid {generate_uuid()})
  )
  (text "PA0: ADC Input (Temperature)\\nPA6: PWM Output (TIM3_CH1)\\nPA9/PA10: UART Debug @ 115200" 
    (at 45.72 106.68 0)
    (effects (font (size 1.016 1.016)) (justify left bottom))
    (uuid {generate_uuid()})
  )

  (symbol (lib_id "Sensor_Temperature:LM35") (at 50.8 81.28 0) (unit 1)
    (in_bom yes) (on_board yes) (dnp no)
    (uuid {generate_uuid()})
    (property "Reference" "U2" (at 45.72 73.66 0)
      (effects (font (size 1.27 1.27)) (justify left))
    )
    (property "Value" "LM35" (at 45.72 76.2 0)
      (effects (font (size 1.27 1.27)) (justify left))
    )
    (property "Footprint" "Package_TO_SOT_THT:TO-92_Inline" (at 50.8 83.82 0)
      (effects (font (size 1.27 1.27)) hide)
    )
    (pin "1" (uuid {generate_uuid()}))
    (pin "2" (uuid {generate_uuid()}))
    (pin "3" (uuid {generate_uuid()}))
  )

  (symbol (lib_id "MCU_ST_STM32F1:STM32F103C8Tx") (at 88.9 73.66 0) (unit 1)
    (in_bom yes) (on_board yes) (dnp no)
    (uuid {generate_uuid()})
    (property "Reference" "U1" (at 88.9 33.02 0)
      (effects (font (size 1.27 1.27)))
    )
    (property "Value" "STM32F103C8T6" (at 88.9 35.56 0)
      (effects (font (size 1.27 1.27)))
    )
    (property "Footprint" "Package_QFP:LQFP-48_7x7mm_P0.5mm" (at 88.9 116.84 0)
      (effects (font (size 1.27 1.27)) hide)
    )
    (pin "1" (uuid {generate_uuid()}))
    (pin "2" (uuid {generate_uuid()}))
    (pin "10" (uuid {generate_uuid()}))
    (pin "16" (uuid {generate_uuid()}))
    (pin "30" (uuid {generate_uuid()}))
    (pin "31" (uuid {generate_uuid()}))
  )

  (symbol (lib_id "Device:R") (at 123.19 76.2 90) (unit 1)
    (in_bom yes) (on_board yes) (dnp no)
    (uuid {generate_uuid()})
    (property "Reference" "R1" (at 123.19 71.12 90)
      (effects (font (size 1.27 1.27)))
    )
    (property "Value" "1k" (at 123.19 73.66 90)
      (effects (font (size 1.27 1.27)))
    )
    (property "Footprint" "Resistor_THT:R_Axial_DIN0207_L6.3mm_D2.5mm_P10.16mm_Horizontal" (at 123.19 77.978 0)
      (effects (font (size 1.27 1.27)) hide)
    )
    (pin "1" (uuid {generate_uuid()}))
    (pin "2" (uuid {generate_uuid()}))
  )

  (symbol (lib_id "Transistor_BJT:2N2222") (at 137.16 83.82 0) (unit 1)
    (in_bom yes) (on_board yes) (dnp no)
    (uuid {generate_uuid()})
    (property "Reference" "Q1" (at 142.24 80.01 0)
      (effects (font (size 1.27 1.27)) (justify left))
    )
    (property "Value" "2N2222" (at 142.24 82.55 0)
      (effects (font (size 1.27 1.27)) (justify left))
    )
    (property "Footprint" "Package_TO_SOT_THT:TO-92_Inline" (at 142.24 85.725 0)
      (effects (font (size 1.27 1.27) italic) (justify left) hide)
    )
    (pin "1" (uuid {generate_uuid()}))
    (pin "2" (uuid {generate_uuid()}))
    (pin "3" (uuid {generate_uuid()}))
  )

  (symbol (lib_id "Diode:1N4007") (at 165.1 85.09 270) (unit 1)
    (in_bom yes) (on_board yes) (dnp no)
    (uuid {generate_uuid()})
    (property "Reference" "D1" (at 167.64 83.82 90)
      (effects (font (size 1.27 1.27)) (justify left))
    )
    (property "Value" "1N4007" (at 167.64 86.36 90)
      (effects (font (size 1.27 1.27)) (justify left))
    )
    (property "Footprint" "Diode_THT:D_DO-41_SOD81_P10.16mm_Horizontal" (at 160.655 85.09 0)
      (effects (font (size 1.27 1.27)) hide)
    )
    (pin "1" (uuid {generate_uuid()}))
    (pin "2" (uuid {generate_uuid()}))
  )

  (symbol (lib_id "Motor:Motor_DC") (at 165.1 72.39 0) (unit 1)
    (in_bom yes) (on_board yes) (dnp no)
    (uuid {generate_uuid()})
    (property "Reference" "M1" (at 170.18 68.58 0)
      (effects (font (size 1.27 1.27)) (justify left))
    )
    (property "Value" "DC_Fan" (at 170.18 71.12 0)
      (effects (font (size 1.27 1.27)) (justify left))
    )
    (property "Footprint" "" (at 165.1 74.676 0)
      (effects (font (size 1.27 1.27)) hide)
    )
    (pin "1" (uuid {generate_uuid()}))
    (pin "2" (uuid {generate_uuid()}))
  )

  (symbol (lib_id "power:+5V") (at 165.1 55.88 0) (unit 1)
    (in_bom yes) (on_board yes) (dnp no)
    (uuid {generate_uuid()})
    (property "Reference" "#PWR01" (at 165.1 59.69 0)
      (effects (font (size 1.27 1.27)) hide)
    )
    (property "Value" "+5V" (at 165.1 52.07 0)
      (effects (font (size 1.27 1.27)))
    )
    (pin "1" (uuid {generate_uuid()}))
  )

  (symbol (lib_id "power:GND") (at 142.24 93.98 0) (unit 1)
    (in_bom yes) (on_board yes) (dnp no)
    (uuid {generate_uuid()})
    (property "Reference" "#PWR02" (at 142.24 100.33 0)
      (effects (font (size 1.27 1.27)) hide)
    )
    (property "Value" "GND" (at 142.24 97.79 0)
      (effects (font (size 1.27 1.27)))
    )
    (pin "1" (uuid {generate_uuid()}))
  )

  (sheet_instances
    (path "/" (page "1"))
  )
)
'''
    
    return schematic_content

def export_schematic():
    """Create the KiCad schematic and export to various formats"""
    
    print("=" * 80)
    print("STM32F103C8 Fan Control System - KiCad Schematic Generator")
    print("=" * 80)
    print()
    
    # Generate the schematic file
    print("[Step 1/4] Generating KiCad schematic...")
    schematic_content = create_kicad_schematic()
    
    output_file = "RTS_FanControl.kicad_sch"
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(schematic_content)
    
    print(f"✓ Schematic generated → {output_file}")
    print()
    
    # Create report outputs directory
    print("[Step 2/4] Creating report outputs directory...")
    os.makedirs("report_outputs", exist_ok=True)
    print("✓ Directory created → report_outputs/")
    print()
    
    # Export to PDF using KiCad CLI (if available)
    print("[Step 3/4] Attempting to export schematic to PDF/SVG...")
    print("Note: This requires KiCad CLI to be installed and in PATH")
    
    try:
        # Try to export PDF
        pdf_cmd = f'kicad-cli sch export pdf "{output_file}" -o "report_outputs/{output_file.replace(".kicad_sch", ".pdf")}"'
        result = os.system(pdf_cmd)
        if result == 0:
            print("✓ PDF exported → report_outputs/RTS_FanControl.pdf")
        else:
            print("⚠ PDF export failed (KiCad CLI may not be installed)")
    except Exception as e:
        print(f"⚠ PDF export failed: {e}")
    
    try:
        # Try to export SVG
        svg_cmd = f'kicad-cli sch export svg "{output_file}" -o "report_outputs/"'
        result = os.system(svg_cmd)
        if result == 0:
            print("✓ SVG exported → report_outputs/RTS_FanControl.svg")
        else:
            print("⚠ SVG export failed (KiCad CLI may not be installed)")
    except Exception as e:
        print(f"⚠ SVG export failed: {e}")
    
    print()
    
    # Summary
    print("[Step 4/4] Summary")
    print("=" * 80)
    print("Schematic File Components:")
    print("  - STM32F103C8T6 microcontroller (U1)")
    print("  - LM35 temperature sensor (U2) - simulated in software")
    print("  - 2N2222 NPN transistor (Q1)")
    print("  - 1kΩ base resistor (R1)")
    print("  - 1N4007 flyback diode (D1)")
    print("  - DC cooling fan motor (M1)")
    print("  - +5V and GND power rails")
    print()
    print("Pin Connections:")
    print("  - PA0: ADC input for temperature sensor")
    print("  - PA6: PWM output (TIM3_CH1) @ 8kHz")
    print("  - PA9: UART TX for debug output")
    print("  - PA10: UART RX for debug input")
    print()
    print("Control Algorithm:")
    print("  - Proportional control: Fan Speed = Temperature × 40%")
    print("  - Temperature range: 25°C to 100°C")
    print("  - PWM duty cycle: 0-4000 (0-100%)")
    print()
    print("Files Generated:")
    print(f"  ✓ {output_file} (KiCad schematic)")
    print("  ✓ report_outputs/ (exports directory)")
    print()
    print("Next Steps:")
    print("  1. Open RTS_FanControl.kicad_sch in KiCad to view/edit")
    print("  2. Use KiCad's built-in tools to export to PDF/PNG if CLI failed")
    print("  3. Include the schematic in your project report")
    print()
    print("=" * 80)
    print("✓ Schematic generation complete!")
    print("=" * 80)

if __name__ == "__main__":
    export_schematic()
